{"log_level": 0, "text": "https://192.168.7.157/vedsdk/Authorize: {\"Username\": \"local:admin\", \"Password\": \"newPassw0rd!\"}", "filename": "session.py", "source": "16:\t    def post(self, url, data, verify=False):\n17:\t        self._logger.log('%s: %s' %(url, data))\n18:\t        return requests.post(url=url, data=data, headers=self.headers, verify=verify)\n", "lineno": "17", "path": "C:\\Users\\LL\\PycharmProjects\\NewFoundation\\apilibs"}
{"log_level": 0, "text": "https://192.168.7.157/aperture/api/users/authorize: {\"username\": \"local:admin\", \"password\": \"newPassw0rd!\"}", "filename": "session.py", "source": "16:\t    def post(self, url, data, verify=False):\n17:\t        self._logger.log('%s: %s' %(url, data))\n18:\t        return requests.post(url=url, data=data, headers=self.headers, verify=verify)\n", "lineno": "17", "path": "C:\\Users\\LL\\PycharmProjects\\NewFoundation\\apilibs"}
{"log_level": 9, "text": "<span style=\"white-space: pre-wrap; color: red\">Traceback (most recent call last):\n  File \"C:/Users/LL/PycharmProjects/NewFoundation/testfile.py\", line 84, in <module>\n    x.create_many_folders()\n  File \"C:/Users/LL/PycharmProjects/NewFoundation/testfile.py\", line 76, in create_many_folders\n    folder = Folder(self.auth)\nTypeError: __init__() takes exactly 5 arguments (2 given)\n</span>", "filename": "testfile.py", "source": "75:\t    def create_many_folders(self):\n76:\t        folder = Folder(self.auth)\n77:\t        folders = folder.create('tyler', r'\\VED\\Policy', num_objects=5)\n78:\t        print(folders)\n", "lineno": "76", "path": "C:/Users/LL/PycharmProjects/NewFoundation"}
